# FROM docker.io/library/golang:1.26.2-alpine3.23 AS golang
# FROM docker.io/library/swift:6.0.3 AS swift

# FROM golang AS build
# WORKDIR /workspace
# COPY go.mod go.sum ./
# RUN go mod download
# COPY . .
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server .

# FROM swift AS run
# WORKDIR /workspace
# COPY --from=build /workspace/server .
# COPY --from=build /workspace/docs ./docs
# CMD ./server
# EXPOSE 1323
