FROM docker.io/library/golang:1.26.2-alpine3.23 AS golang
FROM docker.io/library/eclipse-temurin:21.0.6_7-jdk-alpine-3.21 AS jdk

FROM golang AS build
WORKDIR /workspace
RUN go install github.com/swaggo/swag/cmd/swag@v1.16.4
COPY go.mod go.sum ./
RUN go mod download -x
COPY . .
RUN swag init
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server .

FROM jdk AS run
RUN apk update && apk add bash && \
    cd /usr/lib && \
    wget -q https://github.com/JetBrains/kotlin/releases/download/v2.1.10/kotlin-compiler-2.1.10.zip && \
    unzip -q kotlin-compiler* && \
    rm kotlin-compiler* && \
    rm -f kotlinc/bin/*.bat && \
    export PATH=$PATH:/usr/lib/kotlinc/bin

WORKDIR /workspace
COPY .oci /root/.oci
COPY .env .
COPY --from=build /workspace/server .
COPY --from=build /workspace/docs ./docs
CMD ./server
EXPOSE 1323
